### ISSUE TITLE
Tip of master does not appear to compile?

### ISSUE THREAD

**Issue by iqbal-lab** [simongog/sdsl-lite#303]
1. git clone https://github.com/simongog/sdsl-lite.git
Initialized empty Git repository in /Net/fs1/home/zam/dev/git/sdsl-lite/.git/
remote: Counting objects: 12888, done.
remote: Total 12888 (delta 0), reused 0 (delta 0), pack-reused 12888
Receiving objects: 100% (12888/12888), 9.01 MiB | 3.39 MiB/s, done.
Resolving deltas: 100% (7357/7357), done.

So far so good.

cd sdsl-lite/
bash-4.1$ ./install.sh 
Library will be installed in '/Net/fs1/home/zam'
Copy pre-commit into .git/hooks
-- The CXX compiler identification is GNU 4.7.2
-- The C compiler identification is GNU 4.7.2
-- Check for working CXX compiler: /opt/centos/devtoolset-1.1/root/usr/bin/c++
-- Check for working CXX compiler: /opt/centos/devtoolset-1.1/root/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /opt/centos/devtoolset-1.1/root/usr/bin/cc
-- Check for working C compiler: /opt/centos/devtoolset-1.1/root/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Compiler is recent enough to support C++11.
-- Performing Test HAVE_GCC_STD=C__11__WALL__WEXTRA___DNDEBUG
-- Performing Test HAVE_GCC_STD=C__11__WALL__WEXTRA___DNDEBUG - Success
-- Performing Test HAVE_GCC_O3__FFAST_MATH__FUNROLL_LOOPS
-- Performing Test HAVE_GCC_O3__FFAST_MATH__FUNROLL_LOOPS - Success
-- Performing Test HAVE_GCC_MSSE4.2
-- Performing Test HAVE_GCC_MSSE4.2 - Success
CMake Warning (dev) at external/libdivsufsort/CMakeLists.txt:7 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    PROJECT_VERSION
    PROJECT_VERSION_MAJOR
    PROJECT_VERSION_MINOR
    PROJECT_VERSION_PATCH
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Performing Test HAVE_GCC_WALL
-- Performing Test HAVE_GCC_WALL - Success
-- Performing Test HAVE_GCC_FOMIT_FRAME_POINTER
-- Performing Test HAVE_GCC_FOMIT_FRAME_POINTER - Success
-- Looking for inttypes.h
-- Looking for inttypes.h - found
-- Looking for memory.h
-- Looking for memory.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stdlib.h
-- Looking for stdlib.h - found
-- Looking for string.h
-- Looking for string.h - found
-- Looking for strings.h
-- Looking for strings.h - found
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Performing Test HAVE_INLINE
-- Performing Test HAVE_INLINE - Success
-- Performing Test HAVE___INLINE
-- Performing Test HAVE___INLINE - Success
-- Performing Test HAVE___INLINE__
-- Performing Test HAVE___INLINE__ - Success
-- Performing Test HAVE___DECLSPEC_DLLEXPORT_
-- Performing Test HAVE___DECLSPEC_DLLEXPORT_ - Failed
-- Performing Test HAVE___DECLSPEC_DLLIMPORT_
-- Performing Test HAVE___DECLSPEC_DLLIMPORT_ - Failed
-- Check size of uint8_t
-- Check size of uint8_t - done
-- Check size of int32_t
-- Check size of int32_t - done
-- Looking for PRId32
-- Looking for PRId32 - found
-- Check size of int64_t
-- Check size of int64_t - done
-- Looking for PRId64
-- Looking for PRId64 - found
CMake Warning (dev) at external/googletest/CMakeLists.txt:42 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    PROJECT_VERSION
    PROJECT_VERSION_MAJOR
    PROJECT_VERSION_MINOR
    PROJECT_VERSION_PATCH
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found PythonInterp: /apps/well/python/2.7.7-venv/bin/python (found version "2.7.7") 
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Looking for C++ include cstdio
-- Looking for C++ include cstdio - found
-- Found Doxygen: /usr/bin/doxygen (found version "1.6.1") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/zam/dev/git/sdsl-lite/build
make: Warning: File `Makefile' has modification time 68 s in the future
make[1]: Warning: File `CMakeFiles/Makefile2' has modification time 78 s in the future
make[2]: Warning: File `CMakeFiles/Makefile2' has modification time 78 s in the future
make[3]: Warning: File `lib/CMakeFiles/sdsl.dir/flags.make' has modification time 68 s in the future
Scanning dependencies of target sdsl
make[3]: warning:  Clock skew detected.  Your build may be incomplete.
make[3]: Warning: File `lib/CMakeFiles/sdsl.dir/flags.make' has modification time 68 s in the future
[  0%] Building CXX object lib/CMakeFiles/sdsl.dir/bits.cpp.o
[  0%] Building CXX object lib/CMakeFiles/sdsl.dir/bp_support_algorithm.cpp.o
[  0%] Building CXX object lib/CMakeFiles/sdsl.dir/coder_elias_delta.cpp.o
[ 14%] Building CXX object lib/CMakeFiles/sdsl.dir/coder_elias_gamma.cpp.o
[ 14%] Building CXX object lib/CMakeFiles/sdsl.dir/coder_fibonacci.cpp.o
[ 14%] Building CXX object lib/CMakeFiles/sdsl.dir/config.cpp.o
[ 28%] Building CXX object lib/CMakeFiles/sdsl.dir/construct_config.cpp.o
[ 28%] Building CXX object lib/CMakeFiles/sdsl.dir/construct_isa.cpp.o
[ 28%] Building CXX object lib/CMakeFiles/sdsl.dir/construct_lcp.cpp.o

also as far as  I can see, so far so good.

In file included from /home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_huff.hpp:25:0,
                 from /home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/construct_lcp.hpp:33,
                 from /home/zam/dev/git/sdsl-lite/lib/construct_lcp.cpp:6:
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_pc.hpp: In member function ‘std::array<std::vector<std::array<long unsigned int, 2ul> >, 2ul> sdsl::wt_pc<t_shape, t_bitvector, t_rank, t_select, t_select_zero, t_tree_strat>::expand(const node_type&, const range_vec_type&) const’:
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_pc.hpp:744:52: error: return type ‘struct std::array<std::vector<std::array<long unsigned int, 2ul> >, 2ul>’ is incomplete
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_pc.hpp: In member function ‘std::array<std::vector<std::array<long unsigned int, 2ul> >, 2ul> sdsl::wt_pc<t_shape, t_bitvector, t_rank, t_select, t_select_zero, t_tree_strat>::expand(const node_type&, sdsl::range_vec_type&&) const’:
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_pc.hpp:761:47: error: return type ‘struct std::array<std::vector<std::array<long unsigned int, 2ul> >, 2ul>’ is incomplete
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_pc.hpp:766:67: error: no match for ‘operator[]’ in ‘r[0]’
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_pc.hpp:767:67: error: no match for ‘operator[]’ in ‘r[1]’
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_pc.hpp:769:39: error: no match for ‘operator[]’ in ‘r[1]’
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_pc.hpp:769:44: error: no match for ‘operator[]’ in ‘r[0]’
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_pc.hpp:772:36: error: no match for ‘operator[]’ in ‘r[0]’
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_pc.hpp: In member function ‘std::array<std::array<long unsigned int, 2ul>, 2ul> sdsl::wt_pc<t_shape, t_bitvector, t_rank, t_select, t_select_zero, t_tree_strat>::expand(const node_type&, const range_type&) const’:
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_pc.hpp:791:63: error: return type ‘struct std::array<std::array<long unsigned int, 2ul>, 2ul>’ is incomplete
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_pc.hpp:793:63: error: no match for ‘operator[]’ in ‘r[0]’
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_pc.hpp:794:63: error: no match for ‘operator[]’ in ‘r[1]’
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_pc.hpp:796:35: error: no match for ‘operator[]’ in ‘r[1]’
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_pc.hpp:796:40: error: no match for ‘operator[]’ in ‘r[0]’
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_pc.hpp:799:32: error: no match for ‘operator[]’ in ‘r[0]’
In file included from /home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/construct_lcp.hpp:34:0,
                 from /home/zam/dev/git/sdsl-lite/lib/construct_lcp.cpp:6:
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_algorithm.hpp: In lambda function:
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_algorithm.hpp:72:36: error: no match for ‘operator[]’ in ‘r[1]’
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_algorithm.hpp:72:41: error: no match for ‘operator[]’ in ‘r[0]’
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_algorithm.hpp: In function ‘void sdsl::_interval_symbols_rec(const t_wt&, sdsl::range_type, typename t_wt::size_type&, std::vector<typename t_wt::value_type>&, std::vector<typename t_wt::size_type>&, std::vector<typename t_wt::size_type>&, const typename t_wt::node_type&)’:
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_algorithm.hpp:129:1: error: ‘r’ has incomplete type
In file included from /opt/centos/devtoolset-1.1/root/usr/lib/gcc/x86_64-redhat-linux/4.7.2/../../../../include/c++/4.7.2/functional:56:0,
                 from /opt/centos/devtoolset-1.1/root/usr/lib/gcc/x86_64-redhat-linux/4.7.2/../../../../include/c++/4.7.2/memory:81,
                 from /home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/structure_tree.hpp:13,
                 from /home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/int_vector.hpp:25,
                 from /home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/construct_lcp.hpp:26,
                 from /home/zam/dev/git/sdsl-lite/lib/construct_lcp.cpp:6:
/opt/centos/devtoolset-1.1/root/usr/lib/gcc/x86_64-redhat-linux/4.7.2/../../../../include/c++/4.7.2/tuple:857:42: error: declaration of ‘sdsl::range_type {aka struct std::array<long unsigned int, 2ul>}’
In file included from /home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/construct_lcp.hpp:34:0,
                 from /home/zam/dev/git/sdsl-lite/lib/construct_lcp.cpp:6:
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_algorithm.hpp: In instantiation of ‘void sdsl::_interval_symbols(const t_wt&, typename t_wt::size_type, typename t_wt::size_type, typename t_wt::size_type&, std::vector<typename t_wt::value_type>&, std::vector<typename t_wt::size_type>&, std::vector<typename t_wt::size_type>&) [with t_wt = sdsl::wt_pc<sdsl::huff_shape, sdsl::int_vector<1u>, sdsl::rank_support_v<1u, 1u>, sdsl::select_support_scan<1u>, sdsl::select_support_scan<0u>, sdsl::byte_tree<> >; typename t_wt::size_type = long unsigned int; typename t_wt::value_type = unsigned char; typename t_wt::size_type = long unsigned int]’:
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_algorithm.hpp:216:9:   required from ‘void sdsl::interval_symbols(const t_wt&, typename t_wt::size_type, typename t_wt::size_type, typename t_wt::size_type&, std::vector<typename t_wt::value_type>&, std::vector<typename t_wt::size_type>&, std::vector<typename t_wt::size_type>&) [with t_wt = sdsl::wt_pc<sdsl::huff_shape, sdsl::int_vector<1u>, sdsl::rank_support_v<1u, 1u>, sdsl::select_support_scan<1u>, sdsl::select_support_scan<0u>, sdsl::byte_tree<> >; typename t_wt::size_type = long unsigned int; typename t_wt::value_type = unsigned char; typename t_wt::size_type = long unsigned int]’
/home/zam/dev/git/sdsl-lite/lib/construct_lcp.cpp:681:68:   required from here
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_algorithm.hpp:175:9: error: no matching function for call to ‘_interval_symbols_rec(const sdsl::wt_pc<sdsl::huff_shape, sdsl::int_vector<1u>, sdsl::rank_support_v<1u, 1u>, sdsl::select_support_scan<1u>, sdsl::select_support_scan<0u>, sdsl::byte_tree<> >&, <brace-enclosed initializer list>, sdsl::wt_pc<sdsl::huff_shape, sdsl::int_vector<1u>, sdsl::rank_support_v<1u, 1u>, sdsl::select_support_scan<1u>, sdsl::select_support_scan<0u>, sdsl::byte_tree<> >::size_type&, std::vector<unsigned char>&, std::vector<long unsigned int>&, std::vector<long unsigned int>&, sdsl::wt_pc<sdsl::huff_shape, sdsl::int_vector<1u>, sdsl::rank_support_v<1u, 1u>, sdsl::select_support_scan<1u>, sdsl::select_support_scan<0u>, sdsl::byte_tree<> >::node_type)’
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_algorithm.hpp:175:9: note: candidate is:
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_algorithm.hpp:129:1: note: template<class t_wt> void sdsl::_interval_symbols_rec(const t_wt&, sdsl::range_type, typename t_wt::size_type&, std::vector<typename t_wt::value_type>&, std::vector<typename t_wt::size_type>&, std::vector<typename t_wt::size_type>&, const typename t_wt::node_type&)
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_algorithm.hpp:129:1: note:   template argument deduction/substitution failed:
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_algorithm.hpp:175:9: note:   cannot convert ‘{i, (j + 18446744073709551615ul)}’ (type ‘<brace-enclosed initializer list>’) to type ‘sdsl::range_type {aka std::array<long unsigned int, 2ul>}’
make[3]: *** [lib/CMakeFiles/sdsl.dir/construct_lcp.cpp.o] Error 1
make[2]: *** [lib/CMakeFiles/sdsl.dir/all] Error 2
make[1]: *** [lib/CMakeFiles/sdsl.dir/rule] Error 2
make: *** [sdsl] Error 2
ERROR: Build failed.
bash-4.1$

**Comment by mpetri** [comment]
I suspect this is due to the the change in return type from `std::tuple` to `std::array` which Simon pushed a while ago which does not seem to work with "old" compilers.

**Comment by simongog** [comment]
The initialization of std::array was wrong in one place. It somehow worked with many compilers. I pushed a fix.

**Comment by simongog** [comment]
@iqbal-lab thanks for pointing this out. Is the issue resolved now?

**Comment by iqbal-lab** [comment]
Thanks for looking into this so fast. But no, it is not yet fixed

git clone https://github.com/simongog/sdsl-lite.git
Initialized empty Git repository in /Net/fs1/home/zam/dev/git/sdsl-lite/.git/
remote: Counting objects: 12894, done.
remote: Total 12894 (delta 0), reused 0 (delta 0), pack-reused 12893
Receiving objects: 100% (12894/12894), 9.01 MiB | 3.43 MiB/s, done.
Resolving deltas: 100% (7360/7360), done.


bash-4.1$ cd sdsl-lite/




./install.sh 
Library will be installed in '/Net/fs1/home/zam'
Copy pre-commit into .git/hooks
-- The CXX compiler identification is GNU 4.7.2
-- The C compiler identification is GNU 4.7.2
-- Check for working CXX compiler: /opt/centos/devtoolset-1.1/root/usr/bin/c++
-- Check for working CXX compiler: /opt/centos/devtoolset-1.1/root/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /opt/centos/devtoolset-1.1/root/usr/bin/cc
-- Check for working C compiler: /opt/centos/devtoolset-1.1/root/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Compiler is recent enough to support C++11.
-- Performing Test HAVE_GCC_STD=C__11__WALL__WEXTRA___DNDEBUG
-- Performing Test HAVE_GCC_STD=C__11__WALL__WEXTRA___DNDEBUG - Success
-- Performing Test HAVE_GCC_O3__FFAST_MATH__FUNROLL_LOOPS
-- Performing Test HAVE_GCC_O3__FFAST_MATH__FUNROLL_LOOPS - Success
-- Performing Test HAVE_GCC_MSSE4.2
-- Performing Test HAVE_GCC_MSSE4.2 - Success
CMake Warning (dev) at external/libdivsufsort/CMakeLists.txt:7 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    PROJECT_VERSION
    PROJECT_VERSION_MAJOR
    PROJECT_VERSION_MINOR
    PROJECT_VERSION_PATCH
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Performing Test HAVE_GCC_WALL
-- Performing Test HAVE_GCC_WALL - Success
-- Performing Test HAVE_GCC_FOMIT_FRAME_POINTER
-- Performing Test HAVE_GCC_FOMIT_FRAME_POINTER - Success
-- Looking for inttypes.h
-- Looking for inttypes.h - found
-- Looking for memory.h
-- Looking for memory.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stdlib.h
-- Looking for stdlib.h - found
-- Looking for string.h
-- Looking for string.h - found
-- Looking for strings.h
-- Looking for strings.h - found
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Performing Test HAVE_INLINE
-- Performing Test HAVE_INLINE - Success
-- Performing Test HAVE___INLINE
-- Performing Test HAVE___INLINE - Success
-- Performing Test HAVE___INLINE__
-- Performing Test HAVE___INLINE__ - Success
-- Performing Test HAVE___DECLSPEC_DLLEXPORT_
-- Performing Test HAVE___DECLSPEC_DLLEXPORT_ - Failed
-- Performing Test HAVE___DECLSPEC_DLLIMPORT_
-- Performing Test HAVE___DECLSPEC_DLLIMPORT_ - Failed
-- Check size of uint8_t
-- Check size of uint8_t - done
-- Check size of int32_t
-- Check size of int32_t - done
-- Looking for PRId32
-- Looking for PRId32 - found
-- Check size of int64_t
-- Check size of int64_t - done
-- Looking for PRId64
-- Looking for PRId64 - found
CMake Warning (dev) at external/googletest/CMakeLists.txt:42 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    PROJECT_VERSION
    PROJECT_VERSION_MAJOR
    PROJECT_VERSION_MINOR
    PROJECT_VERSION_PATCH
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found PythonInterp: /apps/well/python/2.7.7-venv/bin/python (found version "2.7.7") 
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Looking for C++ include cstdio
-- Looking for C++ include cstdio - found
-- Found Doxygen: /usr/bin/doxygen (found version "1.6.1") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/zam/dev/git/sdsl-lite/build
make: Warning: File `Makefile' has modification time 71 s in the future
make[1]: Warning: File `CMakeFiles/Makefile2' has modification time 79 s in the future
make[2]: Warning: File `CMakeFiles/Makefile2' has modification time 79 s in the future
make[3]: Warning: File `lib/CMakeFiles/sdsl.dir/flags.make' has modification time 71 s in the future
Scanning dependencies of target sdsl
make[3]: warning:  Clock skew detected.  Your build may be incomplete.
make[3]: Warning: File `lib/CMakeFiles/sdsl.dir/flags.make' has modification time 71 s in the future
[  0%] Building CXX object lib/CMakeFiles/sdsl.dir/bits.cpp.o
[  0%] Building CXX object lib/CMakeFiles/sdsl.dir/bp_support_algorithm.cpp.o
[  0%] Building CXX object lib/CMakeFiles/sdsl.dir/coder_elias_delta.cpp.o
[ 14%] Building CXX object lib/CMakeFiles/sdsl.dir/coder_elias_gamma.cpp.o
[ 14%] Building CXX object lib/CMakeFiles/sdsl.dir/coder_fibonacci.cpp.o
[ 14%] Building CXX object lib/CMakeFiles/sdsl.dir/config.cpp.o
[ 28%] Building CXX object lib/CMakeFiles/sdsl.dir/construct_config.cpp.o
[ 28%] Building CXX object lib/CMakeFiles/sdsl.dir/construct_isa.cpp.o
[ 28%] Building CXX object lib/CMakeFiles/sdsl.dir/construct_lcp.cpp.o
In file included from /home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_huff.hpp:25:0,
                 from /home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/construct_lcp.hpp:33,
                 from /home/zam/dev/git/sdsl-lite/lib/construct_lcp.cpp:6:
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_pc.hpp: In member function ‘std::array<std::vector<std::array<long unsigned int, 2ul> >, 2ul> sdsl::wt_pc<t_shape, t_bitvector, t_rank, t_select, t_select_zero, t_tree_strat>::expand(const node_type&, const range_vec_type&) const’:
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_pc.hpp:744:52: error: return type ‘struct std::array<std::vector<std::array<long unsigned int, 2ul> >, 2ul>’ is incomplete
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_pc.hpp: In member function ‘std::array<std::vector<std::array<long unsigned int, 2ul> >, 2ul> sdsl::wt_pc<t_shape, t_bitvector, t_rank, t_select, t_select_zero, t_tree_strat>::expand(const node_type&, sdsl::range_vec_type&&) const’:
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_pc.hpp:761:47: error: return type ‘struct std::array<std::vector<std::array<long unsigned int, 2ul> >, 2ul>’ is incomplete
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_pc.hpp:766:67: error: no match for ‘operator[]’ in ‘r[0]’
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_pc.hpp:767:67: error: no match for ‘operator[]’ in ‘r[1]’
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_pc.hpp:769:39: error: no match for ‘operator[]’ in ‘r[1]’
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_pc.hpp:769:44: error: no match for ‘operator[]’ in ‘r[0]’
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_pc.hpp:772:36: error: no match for ‘operator[]’ in ‘r[0]’
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_pc.hpp: In member function ‘std::array<std::array<long unsigned int, 2ul>, 2ul> sdsl::wt_pc<t_shape, t_bitvector, t_rank, t_select, t_select_zero, t_tree_strat>::expand(const node_type&, const range_type&) const’:
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_pc.hpp:791:63: error: return type ‘struct std::array<std::array<long unsigned int, 2ul>, 2ul>’ is incomplete
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_pc.hpp:793:63: error: no match for ‘operator[]’ in ‘r[0]’
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_pc.hpp:794:63: error: no match for ‘operator[]’ in ‘r[1]’
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_pc.hpp:796:35: error: no match for ‘operator[]’ in ‘r[1]’
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_pc.hpp:796:40: error: no match for ‘operator[]’ in ‘r[0]’
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_pc.hpp:799:32: error: no match for ‘operator[]’ in ‘r[0]’
In file included from /home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/construct_lcp.hpp:34:0,
                 from /home/zam/dev/git/sdsl-lite/lib/construct_lcp.cpp:6:
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_algorithm.hpp: In lambda function:
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_algorithm.hpp:72:36: error: no match for ‘operator[]’ in ‘r[1]’
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_algorithm.hpp:72:41: error: no match for ‘operator[]’ in ‘r[0]’
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_algorithm.hpp: In function ‘void sdsl::_interval_symbols_rec(const t_wt&, sdsl::range_type, typename t_wt::size_type&, std::vector<typename t_wt::value_type>&, std::vector<typename t_wt::size_type>&, std::vector<typename t_wt::size_type>&, const typename t_wt::node_type&)’:
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_algorithm.hpp:129:1: error: ‘r’ has incomplete type
In file included from /opt/centos/devtoolset-1.1/root/usr/lib/gcc/x86_64-redhat-linux/4.7.2/../../../../include/c++/4.7.2/functional:56:0,
                 from /opt/centos/devtoolset-1.1/root/usr/lib/gcc/x86_64-redhat-linux/4.7.2/../../../../include/c++/4.7.2/memory:81,
                 from /home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/structure_tree.hpp:13,
                 from /home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/int_vector.hpp:25,
                 from /home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/construct_lcp.hpp:26,
                 from /home/zam/dev/git/sdsl-lite/lib/construct_lcp.cpp:6:
/opt/centos/devtoolset-1.1/root/usr/lib/gcc/x86_64-redhat-linux/4.7.2/../../../../include/c++/4.7.2/tuple:857:42: error: declaration of ‘sdsl::range_type {aka struct std::array<long unsigned int, 2ul>}’
In file included from /home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/construct_lcp.hpp:34:0,
                 from /home/zam/dev/git/sdsl-lite/lib/construct_lcp.cpp:6:
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_algorithm.hpp: In instantiation of ‘void sdsl::_interval_symbols(const t_wt&, typename t_wt::size_type, typename t_wt::size_type, typename t_wt::size_type&, std::vector<typename t_wt::value_type>&, std::vector<typename t_wt::size_type>&, std::vector<typename t_wt::size_type>&) [with t_wt = sdsl::wt_pc<sdsl::huff_shape, sdsl::int_vector<1u>, sdsl::rank_support_v<1u, 1u>, sdsl::select_support_scan<1u>, sdsl::select_support_scan<0u>, sdsl::byte_tree<> >; typename t_wt::size_type = long unsigned int; typename t_wt::value_type = unsigned char; typename t_wt::size_type = long unsigned int]’:
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_algorithm.hpp:216:9:   required from ‘void sdsl::interval_symbols(const t_wt&, typename t_wt::size_type, typename t_wt::size_type, typename t_wt::size_type&, std::vector<typename t_wt::value_type>&, std::vector<typename t_wt::size_type>&, std::vector<typename t_wt::size_type>&) [with t_wt = sdsl::wt_pc<sdsl::huff_shape, sdsl::int_vector<1u>, sdsl::rank_support_v<1u, 1u>, sdsl::select_support_scan<1u>, sdsl::select_support_scan<0u>, sdsl::byte_tree<> >; typename t_wt::size_type = long unsigned int; typename t_wt::value_type = unsigned char; typename t_wt::size_type = long unsigned int]’
/home/zam/dev/git/sdsl-lite/lib/construct_lcp.cpp:681:68:   required from here
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_algorithm.hpp:175:9: error: no matching function for call to ‘_interval_symbols_rec(const sdsl::wt_pc<sdsl::huff_shape, sdsl::int_vector<1u>, sdsl::rank_support_v<1u, 1u>, sdsl::select_support_scan<1u>, sdsl::select_support_scan<0u>, sdsl::byte_tree<> >&, <brace-enclosed initializer list>, sdsl::wt_pc<sdsl::huff_shape, sdsl::int_vector<1u>, sdsl::rank_support_v<1u, 1u>, sdsl::select_support_scan<1u>, sdsl::select_support_scan<0u>, sdsl::byte_tree<> >::size_type&, std::vector<unsigned char>&, std::vector<long unsigned int>&, std::vector<long unsigned int>&, sdsl::wt_pc<sdsl::huff_shape, sdsl::int_vector<1u>, sdsl::rank_support_v<1u, 1u>, sdsl::select_support_scan<1u>, sdsl::select_support_scan<0u>, sdsl::byte_tree<> >::node_type)’
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_algorithm.hpp:175:9: note: candidate is:
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_algorithm.hpp:129:1: note: template<class t_wt> void sdsl::_interval_symbols_rec(const t_wt&, sdsl::range_type, typename t_wt::size_type&, std::vector<typename t_wt::value_type>&, std::vector<typename t_wt::size_type>&, std::vector<typename t_wt::size_type>&, const typename t_wt::node_type&)
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_algorithm.hpp:129:1: note:   template argument deduction/substitution failed:
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_algorithm.hpp:175:9: note:   cannot convert ‘{{i, (j + 18446744073709551615ul)}}’ (type ‘<brace-enclosed initializer list>’) to type ‘sdsl::range_type {aka std::array<long unsigned int, 2ul>}’
make[3]: *** [lib/CMakeFiles/sdsl.dir/construct_lcp.cpp.o] Error 1
make[2]: *** [lib/CMakeFiles/sdsl.dir/all] Error 2
make[1]: *** [lib/CMakeFiles/sdsl.dir/rule] Error 2
make: *** [sdsl] Error 2
ERROR: Build failed.
bash-4.1$ 

 git branch
* master

**Comment by simongog** [comment]
Hi @iqbal-lab , now the range_type constructor is used explicitly. Can you please test again?

**Comment by iqbal-lab** [comment]
Sorry @simongog  - same problem still

bash-4.1$ rm -rf sdsl-lite/
bash-4.1$ git clone https://github.com/simongog/sdsl-lite.git
Initialized empty Git repository in /Net/fs1/home/zam/dev/git/sdsl-lite/.git/
remote: Counting objects: 12900, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 12900 (delta 1), reused 0 (delta 0), pack-reused 12893
Receiving objects: 100% (12900/12900), 9.02 MiB | 3.46 MiB/s, done.
Resolving deltas: 100% (7361/7361), done.
bash-4.1$ cd sdsl-lite/
bash-4.1$ less README.md 
bash-4.1$ ./install.sh 
Library will be installed in '/Net/fs1/home/zam'
Copy pre-commit into .git/hooks
-- The CXX compiler identification is GNU 4.7.2
-- The C compiler identification is GNU 4.7.2
-- Check for working CXX compiler: /opt/centos/devtoolset-1.1/root/usr/bin/c++
-- Check for working CXX compiler: /opt/centos/devtoolset-1.1/root/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /opt/centos/devtoolset-1.1/root/usr/bin/cc
-- Check for working C compiler: /opt/centos/devtoolset-1.1/root/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Compiler is recent enough to support C++11.
-- Performing Test HAVE_GCC_STD=C__11__WALL__WEXTRA___DNDEBUG
-- Performing Test HAVE_GCC_STD=C__11__WALL__WEXTRA___DNDEBUG - Success
-- Performing Test HAVE_GCC_O3__FFAST_MATH__FUNROLL_LOOPS
-- Performing Test HAVE_GCC_O3__FFAST_MATH__FUNROLL_LOOPS - Success
-- Performing Test HAVE_GCC_MSSE4.2
-- Performing Test HAVE_GCC_MSSE4.2 - Success
CMake Warning (dev) at external/libdivsufsort/CMakeLists.txt:7 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    PROJECT_VERSION
    PROJECT_VERSION_MAJOR
    PROJECT_VERSION_MINOR
    PROJECT_VERSION_PATCH
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Performing Test HAVE_GCC_WALL
-- Performing Test HAVE_GCC_WALL - Success
-- Performing Test HAVE_GCC_FOMIT_FRAME_POINTER
-- Performing Test HAVE_GCC_FOMIT_FRAME_POINTER - Success
-- Looking for inttypes.h
-- Looking for inttypes.h - found
-- Looking for memory.h
-- Looking for memory.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stdlib.h
-- Looking for stdlib.h - found
-- Looking for string.h
-- Looking for string.h - found
-- Looking for strings.h
-- Looking for strings.h - found
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Performing Test HAVE_INLINE
-- Performing Test HAVE_INLINE - Success
-- Performing Test HAVE___INLINE
-- Performing Test HAVE___INLINE - Success
-- Performing Test HAVE___INLINE__
-- Performing Test HAVE___INLINE__ - Success
-- Performing Test HAVE___DECLSPEC_DLLEXPORT_
-- Performing Test HAVE___DECLSPEC_DLLEXPORT_ - Failed
-- Performing Test HAVE___DECLSPEC_DLLIMPORT_
-- Performing Test HAVE___DECLSPEC_DLLIMPORT_ - Failed
-- Check size of uint8_t
-- Check size of uint8_t - done
-- Check size of int32_t
-- Check size of int32_t - done
-- Looking for PRId32
-- Looking for PRId32 - found
-- Check size of int64_t
-- Check size of int64_t - done
-- Looking for PRId64
-- Looking for PRId64 - found
CMake Warning (dev) at external/googletest/CMakeLists.txt:42 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    PROJECT_VERSION
    PROJECT_VERSION_MAJOR
    PROJECT_VERSION_MINOR
    PROJECT_VERSION_PATCH
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found PythonInterp: /apps/well/python/2.7.7-venv/bin/python (found version "2.7.7") 
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Looking for C++ include cstdio
-- Looking for C++ include cstdio - found
-- Found Doxygen: /usr/bin/doxygen (found version "1.6.1") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/zam/dev/git/sdsl-lite/build
make: Warning: File `Makefile' has modification time 70 s in the future
make[1]: Warning: File `CMakeFiles/Makefile2' has modification time 79 s in the future
make[2]: Warning: File `CMakeFiles/Makefile2' has modification time 78 s in the future
make[3]: Warning: File `lib/CMakeFiles/sdsl.dir/flags.make' has modification time 70 s in the future
Scanning dependencies of target sdsl
make[3]: warning:  Clock skew detected.  Your build may be incomplete.
make[3]: Warning: File `lib/CMakeFiles/sdsl.dir/flags.make' has modification time 69 s in the future
[  0%] Building CXX object lib/CMakeFiles/sdsl.dir/bits.cpp.o
[  0%] Building CXX object lib/CMakeFiles/sdsl.dir/bp_support_algorithm.cpp.o
[  0%] Building CXX object lib/CMakeFiles/sdsl.dir/coder_elias_delta.cpp.o
[ 14%] Building CXX object lib/CMakeFiles/sdsl.dir/coder_elias_gamma.cpp.o
[ 14%] Building CXX object lib/CMakeFiles/sdsl.dir/coder_fibonacci.cpp.o
[ 14%] Building CXX object lib/CMakeFiles/sdsl.dir/config.cpp.o
[ 28%] Building CXX object lib/CMakeFiles/sdsl.dir/construct_config.cpp.o
[ 28%] Building CXX object lib/CMakeFiles/sdsl.dir/construct_isa.cpp.o
[ 28%] Building CXX object lib/CMakeFiles/sdsl.dir/construct_lcp.cpp.o
In file included from /home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_huff.hpp:25:0,
                 from /home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/construct_lcp.hpp:33,
                 from /home/zam/dev/git/sdsl-lite/lib/construct_lcp.cpp:6:
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_pc.hpp: In member function ‘std::array<std::vector<std::array<long unsigned int, 2ul> >, 2ul> sdsl::wt_pc<t_shape, t_bitvector, t_rank, t_select, t_select_zero, t_tree_strat>::expand(const node_type&, const range_vec_type&) const’:
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_pc.hpp:744:52: error: return type ‘struct std::array<std::vector<std::array<long unsigned int, 2ul> >, 2ul>’ is incomplete
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_pc.hpp: In member function ‘std::array<std::vector<std::array<long unsigned int, 2ul> >, 2ul> sdsl::wt_pc<t_shape, t_bitvector, t_rank, t_select, t_select_zero, t_tree_strat>::expand(const node_type&, sdsl::range_vec_type&&) const’:
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_pc.hpp:761:47: error: return type ‘struct std::array<std::vector<std::array<long unsigned int, 2ul> >, 2ul>’ is incomplete
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_pc.hpp:766:67: error: no match for ‘operator[]’ in ‘r[0]’
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_pc.hpp:767:67: error: no match for ‘operator[]’ in ‘r[1]’
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_pc.hpp:769:39: error: no match for ‘operator[]’ in ‘r[1]’
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_pc.hpp:769:44: error: no match for ‘operator[]’ in ‘r[0]’
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_pc.hpp:772:36: error: no match for ‘operator[]’ in ‘r[0]’
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_pc.hpp: In member function ‘std::array<std::array<long unsigned int, 2ul>, 2ul> sdsl::wt_pc<t_shape, t_bitvector, t_rank, t_select, t_select_zero, t_tree_strat>::expand(const node_type&, const range_type&) const’:
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_pc.hpp:791:63: error: return type ‘struct std::array<std::array<long unsigned int, 2ul>, 2ul>’ is incomplete
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_pc.hpp:793:63: error: no match for ‘operator[]’ in ‘r[0]’
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_pc.hpp:794:63: error: no match for ‘operator[]’ in ‘r[1]’
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_pc.hpp:796:35: error: no match for ‘operator[]’ in ‘r[1]’
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_pc.hpp:796:40: error: no match for ‘operator[]’ in ‘r[0]’
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_pc.hpp:799:32: error: no match for ‘operator[]’ in ‘r[0]’
In file included from /home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/construct_lcp.hpp:34:0,
                 from /home/zam/dev/git/sdsl-lite/lib/construct_lcp.cpp:6:
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_algorithm.hpp: In lambda function:
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_algorithm.hpp:72:36: error: no match for ‘operator[]’ in ‘r[1]’
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_algorithm.hpp:72:41: error: no match for ‘operator[]’ in ‘r[0]’
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_algorithm.hpp: In function ‘void sdsl::_interval_symbols_rec(const t_wt&, sdsl::range_type, typename t_wt::size_type&, std::vector<typename t_wt::value_type>&, std::vector<typename t_wt::size_type>&, std::vector<typename t_wt::size_type>&, const typename t_wt::node_type&)’:
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_algorithm.hpp:129:1: error: ‘r’ has incomplete type
In file included from /opt/centos/devtoolset-1.1/root/usr/lib/gcc/x86_64-redhat-linux/4.7.2/../../../../include/c++/4.7.2/functional:56:0,
                 from /opt/centos/devtoolset-1.1/root/usr/lib/gcc/x86_64-redhat-linux/4.7.2/../../../../include/c++/4.7.2/memory:81,
                 from /home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/structure_tree.hpp:13,
                 from /home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/int_vector.hpp:25,
                 from /home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/construct_lcp.hpp:26,
                 from /home/zam/dev/git/sdsl-lite/lib/construct_lcp.cpp:6:
/opt/centos/devtoolset-1.1/root/usr/lib/gcc/x86_64-redhat-linux/4.7.2/../../../../include/c++/4.7.2/tuple:857:42: error: declaration of ‘sdsl::range_type {aka struct std::array<long unsigned int, 2ul>}’
In file included from /home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/construct_lcp.hpp:34:0,
                 from /home/zam/dev/git/sdsl-lite/lib/construct_lcp.cpp:6:
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_algorithm.hpp: In instantiation of ‘void sdsl::_interval_symbols(const t_wt&, typename t_wt::size_type, typename t_wt::size_type, typename t_wt::size_type&, std::vector<typename t_wt::value_type>&, std::vector<typename t_wt::size_type>&, std::vector<typename t_wt::size_type>&) [with t_wt = sdsl::wt_pc<sdsl::huff_shape, sdsl::int_vector<1u>, sdsl::rank_support_v<1u, 1u>, sdsl::select_support_scan<1u>, sdsl::select_support_scan<0u>, sdsl::byte_tree<> >; typename t_wt::size_type = long unsigned int; typename t_wt::value_type = unsigned char; typename t_wt::size_type = long unsigned int]’:
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_algorithm.hpp:216:9:   required from ‘void sdsl::interval_symbols(const t_wt&, typename t_wt::size_type, typename t_wt::size_type, typename t_wt::size_type&, std::vector<typename t_wt::value_type>&, std::vector<typename t_wt::size_type>&, std::vector<typename t_wt::size_type>&) [with t_wt = sdsl::wt_pc<sdsl::huff_shape, sdsl::int_vector<1u>, sdsl::rank_support_v<1u, 1u>, sdsl::select_support_scan<1u>, sdsl::select_support_scan<0u>, sdsl::byte_tree<> >; typename t_wt::size_type = long unsigned int; typename t_wt::value_type = unsigned char; typename t_wt::size_type = long unsigned int]’
/home/zam/dev/git/sdsl-lite/lib/construct_lcp.cpp:681:68:   required from here
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_algorithm.hpp:175:9: error: too many initializers for ‘sdsl::range_type {aka std::array<long unsigned int, 2ul>}’
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_algorithm.hpp:175:9: error: invalid use of incomplete type ‘sdsl::range_type {aka struct std::array<long unsigned int, 2ul>}’
In file included from /opt/centos/devtoolset-1.1/root/usr/lib/gcc/x86_64-redhat-linux/4.7.2/../../../../include/c++/4.7.2/functional:56:0,
                 from /opt/centos/devtoolset-1.1/root/usr/lib/gcc/x86_64-redhat-linux/4.7.2/../../../../include/c++/4.7.2/memory:81,
                 from /home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/structure_tree.hpp:13,
                 from /home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/int_vector.hpp:25,
                 from /home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/construct_lcp.hpp:26,
                 from /home/zam/dev/git/sdsl-lite/lib/construct_lcp.cpp:6:
/opt/centos/devtoolset-1.1/root/usr/lib/gcc/x86_64-redhat-linux/4.7.2/../../../../include/c++/4.7.2/tuple:857:42: error: declaration of ‘sdsl::range_type {aka struct std::array<long unsigned int, 2ul>}’
make[3]: *** [lib/CMakeFiles/sdsl.dir/construct_lcp.cpp.o] Error 1
make[2]: *** [lib/CMakeFiles/sdsl.dir/all] Error 2
make[1]: *** [lib/CMakeFiles/sdsl.dir/rule] Error 2
make: *** [sdsl] Error 2
ERROR: Build failed.

**Comment by iqbal-lab** [comment]
I'm not being dumb am I? It's master I'm meant to be testing?

**Comment by simongog** [comment]
Yes, it's master. I have added one include. Maybe this fixes the problem.

**Comment by iqbal-lab** [comment]
Apologies Simon - no change


git log | head -n 10
commit 668c96b63bd60019b33efacdba8ca955dd6d02ef
Merge: 9a56dc9 f0b7eb3
Author: Simon Gog <simon.gog@gmail.com>
Date:   Thu Jan 28 15:23:34 2016 +0100

    Merge pull request #306 from simongog/fix303
    
    Address issue #303 again


[ 28%] Building CXX object lib/CMakeFiles/sdsl.dir/construct_isa.cpp.o
[ 28%] Building CXX object lib/CMakeFiles/sdsl.dir/construct_lcp.cpp.o
In file included from /home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_huff.hpp:25:0,
                 from /home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/construct_lcp.hpp:33,
                 from /home/zam/dev/git/sdsl-lite/lib/construct_lcp.cpp:6:
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_pc.hpp: In member function ‘std::array<std::vector<std::array<long unsigned int, 2ul> >, 2ul> sdsl::wt_pc<t_shape, t_bitvector, t_rank, t_select, t_select_zero, t_tree_strat>::expand(const node_type&, const range_vec_type&) const’:
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_pc.hpp:744:52: error: return type ‘struct std::array<std::vector<std::array<long unsigned int, 2ul> >, 2ul>’ is incomplete
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_pc.hpp: In member function ‘std::array<std::vector<std::array<long unsigned int, 2ul> >, 2ul> sdsl::wt_pc<t_shape, t_bitvector, t_rank, t_select, t_select_zero, t_tree_strat>::expand(const node_type&, sdsl::range_vec_type&&) const’:
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_pc.hpp:761:47: error: return type ‘struct std::array<std::vector<std::array<long unsigned int, 2ul> >, 2ul>’ is incomplete
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_pc.hpp:766:67: error: no match for ‘operator[]’ in ‘r[0]’
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_pc.hpp:767:67: error: no match for ‘operator[]’ in ‘r[1]’
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_pc.hpp:769:39: error: no match for ‘operator[]’ in ‘r[1]’
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_pc.hpp:769:44: error: no match for ‘operator[]’ in ‘r[0]’
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_pc.hpp:772:36: error: no match for ‘operator[]’ in ‘r[0]’
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_pc.hpp: In member function ‘std::array<std::array<long unsigned int, 2ul>, 2ul> sdsl::wt_pc<t_shape, t_bitvector, t_rank, t_select, t_select_zero, t_tree_strat>::expand(const node_type&, const range_type&) const’:
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_pc.hpp:791:63: error: return type ‘struct std::array<std::array<long unsigned int, 2ul>, 2ul>’ is incomplete
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_pc.hpp:793:63: error: no match for ‘operator[]’ in ‘r[0]’
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_pc.hpp:794:63: error: no match for ‘operator[]’ in ‘r[1]’
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_pc.hpp:796:35: error: no match for ‘operator[]’ in ‘r[1]’
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_pc.hpp:796:40: error: no match for ‘operator[]’ in ‘r[0]’
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_pc.hpp:799:32: error: no match for ‘operator[]’ in ‘r[0]’
In file included from /home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/construct_lcp.hpp:34:0,
                 from /home/zam/dev/git/sdsl-lite/lib/construct_lcp.cpp:6:
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_algorithm.hpp: In lambda function:
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_algorithm.hpp:73:36: error: no match for ‘operator[]’ in ‘r[1]’
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_algorithm.hpp:73:41: error: no match for ‘operator[]’ in ‘r[0]’
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_algorithm.hpp: In function ‘void sdsl::_interval_symbols_rec(const t_wt&, sdsl::range_type, typename t_wt::size_type&, std::vector<typename t_wt::value_type>&, std::vector<typename t_wt::size_type>&, std::vector<typename t_wt::size_type>&, const typename t_wt::node_type&)’:
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_algorithm.hpp:130:1: error: ‘r’ has incomplete type
In file included from /opt/centos/devtoolset-1.1/root/usr/lib/gcc/x86_64-redhat-linux/4.7.2/../../../../include/c++/4.7.2/functional:56:0,
                 from /opt/centos/devtoolset-1.1/root/usr/lib/gcc/x86_64-redhat-linux/4.7.2/../../../../include/c++/4.7.2/memory:81,
                 from /home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/structure_tree.hpp:13,
                 from /home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/int_vector.hpp:25,
                 from /home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/construct_lcp.hpp:26,
                 from /home/zam/dev/git/sdsl-lite/lib/construct_lcp.cpp:6:
/opt/centos/devtoolset-1.1/root/usr/lib/gcc/x86_64-redhat-linux/4.7.2/../../../../include/c++/4.7.2/tuple:857:42: error: declaration of ‘sdsl::range_type {aka struct std::array<long unsigned int, 2ul>}’
In file included from /home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/construct_lcp.hpp:34:0,
                 from /home/zam/dev/git/sdsl-lite/lib/construct_lcp.cpp:6:
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_algorithm.hpp: In instantiation of ‘void sdsl::_interval_symbols(const t_wt&, typename t_wt::size_type, typename t_wt::size_type, typename t_wt::size_type&, std::vector<typename t_wt::value_type>&, std::vector<typename t_wt::size_type>&, std::vector<typename t_wt::size_type>&) [with t_wt = sdsl::wt_pc<sdsl::huff_shape, sdsl::int_vector<1u>, sdsl::rank_support_v<1u, 1u>, sdsl::select_support_scan<1u>, sdsl::select_support_scan<0u>, sdsl::byte_tree<> >; typename t_wt::size_type = long unsigned int; typename t_wt::value_type = unsigned char; typename t_wt::size_type = long unsigned int]’:
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_algorithm.hpp:217:9:   required from ‘void sdsl::interval_symbols(const t_wt&, typename t_wt::size_type, typename t_wt::size_type, typename t_wt::size_type&, std::vector<typename t_wt::value_type>&, std::vector<typename t_wt::size_type>&, std::vector<typename t_wt::size_type>&) [with t_wt = sdsl::wt_pc<sdsl::huff_shape, sdsl::int_vector<1u>, sdsl::rank_support_v<1u, 1u>, sdsl::select_support_scan<1u>, sdsl::select_support_scan<0u>, sdsl::byte_tree<> >; typename t_wt::size_type = long unsigned int; typename t_wt::value_type = unsigned char; typename t_wt::size_type = long unsigned int]’
/home/zam/dev/git/sdsl-lite/lib/construct_lcp.cpp:681:68:   required from here
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_algorithm.hpp:176:9: error: too many initializers for ‘sdsl::range_type {aka std::array<long unsigned int, 2ul>}’
/home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/wt_algorithm.hpp:176:9: error: invalid use of incomplete type ‘sdsl::range_type {aka struct std::array<long unsigned int, 2ul>}’
In file included from /opt/centos/devtoolset-1.1/root/usr/lib/gcc/x86_64-redhat-linux/4.7.2/../../../../include/c++/4.7.2/functional:56:0,
                 from /opt/centos/devtoolset-1.1/root/usr/lib/gcc/x86_64-redhat-linux/4.7.2/../../../../include/c++/4.7.2/memory:81,
                 from /home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/structure_tree.hpp:13,
                 from /home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/int_vector.hpp:25,
                 from /home/zam/dev/git/sdsl-lite/build/lib/../include/sdsl/construct_lcp.hpp:26,
                 from /home/zam/dev/git/sdsl-lite/lib/construct_lcp.cpp:6:
/opt/centos/devtoolset-1.1/root/usr/lib/gcc/x86_64-redhat-linux/4.7.2/../../../../include/c++/4.7.2/tuple:857:42: error: declaration of ‘sdsl::range_type {aka struct std::array<long unsigned int, 2ul>}’
make[3]: *** [lib/CMakeFiles/sdsl.dir/construct_lcp.cpp.o] Error 1
make[2]: *** [lib/CMakeFiles/sdsl.dir/all] Error 2
make[1]: *** [lib/CMakeFiles/sdsl.dir/rule] Error 2
make: *** [sdsl] Error 2
ERROR: Build failed.
bash-4.1$

**Comment by giovmanz** [comment]
I had a similar problem: upgrading gcc from 4.7.2 to 4.9.2 fixed it.

**Comment by simongog** [comment]
This issue is probably also fixed now by adding the missing include of std::array.

**Comment by iqbal-lab** [comment]
Apologies for delay, will retest
